### ISSUE TITLE
Disable Firm Protect

### ISSUE THREAD

**Issue by Committee** [Reisyukaku/ReiNand#40]
Is there any way to disable eshop/firm protection for just one session? Scenario would be if I want to update a game via the Y/Eshop method.

**Comment by Reisyukaku** [comment]
Why would you need to? firm prot only patches an AM service call for firminstall, and the eshop patch is for version check since ninja requires latest version to connect. Neither of these should effect updating a game since they use different AM calls.But if you insist, you'd have to grab my fork of 3ds_injector and comment out the patches in patcher.c. They should be self explanatory.

**Comment by Committee** [comment]
Got it, thank you for the response! :)
