### ISSUE TITLE
Considering of supporting FW 11.3?

### ISSUE THREAD

**Issue by Jerry-Shaw** [Reisyukaku/ReiNand#68]
Still using ReiNAND now. But got black screen after updating to 11.3. Any ideas?

**Comment by CrimsonMaple** [comment]
ReiNand cant boot a 11.3 nfirm. So it black screens. I was just about to open an issue on this. So here is the run down. Homemenu now requires an 11.3 NATIVE_FIRM to boot. So if the homemenu detects a 10.2 firm (like rn's) it wont boot. This effectively patches RN, Corbenik, CakesFW, and parts of Luma. (Luma still technically works due to it booting from the nand directly but I digress.) It's an issue, we noticed and are addressing it.

**Comment by Jerry-Shaw** [comment]
I just go over from GBATemp, notice that. FW 11.3 patchs booting from an external firmware and requires NATIVE_FIRM of 11.3. Hmm... That takes time.

How can Luma do that? I just test all the cfw I have, all failed except Luma.

**Comment by jcmejia** [comment]
Besides all that it missed up the resolution on gba titles as well

**Comment by jcmejia** [comment]
But only applies to cfw

**Comment by darklite404** [comment]
I wish he/she will update it soon.
My n3ds still on Reinand 4.1 since it still support 11.2.0-35

**Comment by Reisyukaku** [comment]
see issue #69
